// <auto-generated />
using Api.Esg.Fiap.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Api.Esg.Fiap.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Esg.Fiap.Models.ColetaModel", b =>
                {
                    b.Property<int>("ColetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColetaId"));

                    b.Property<double>("CapacidadeMax")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("PontoColeta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<double>("QtdAtual")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("ColetaId");

                    b.ToTable("Coletas", (string)null);
                });

            modelBuilder.Entity("Api.Esg.Fiap.Models.ResiduoModel", b =>
                {
                    b.Property<int>("ResiduoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResiduoId"));

                    b.Property<string>("NomeResiduo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<double>("Peso")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("TipoResiduo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("ResiduoId");

                    b.ToTable("Residuos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
